name: deploy plugin

on:
  workflow_dispatch:
    inputs:
      deployment_type:
        description: 'stable or testing'
        type: choice
        required: true
        default: 'testing'
        options:
          - stable
          - testing
      version:
        description: 'version (e.g. 1.0.0.0)'
        type: string
        required: true
      open_pr:
        description: 'should a pr be opened for the deployment?'
        type: boolean
        required: false
        default: false

jobs:
  prepare-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: configure inputs
        id: configure-inputs
        env:
          DEPLOYMENT_TYPE: ${{ inputs.deployment_type }}
        run: |
          if [[ $DEPLOYMENT_TYPE == 'testing' ]]; then
              echo "deployment_type=testing/live" >> $GITHUB_OUTPUT
          else
              echo "deployment_type=$DEPLOYMENT_TYPE" >> $GITHUB_OUTPUT
          fi
    outputs:
      deployment_type: ${{ steps.configure-inputs.outputs.deployment_type }}

  deploy-plugin:
    uses: kalilistic/DalamudPluginDeploy/.github/workflows/deploy_plugin.yml@7dd6a4952a96ad4b3b5b0c61ab90e64fd09f1c4e
    needs: prepare-deploy
    with:
      public_name: 'ScoutHelper'
      internal_name: 'ScoutHelper'
      project_dir: 'ScoutHelper'
      project_name: 'ScoutHelper'
      github_username: 'dit-zy'
      github_email: 'dit.zy@pm.com'
      open_pr: ${{ inputs.open_pr }}
      deployment_type: ${{ needs.prepare-deploy.outputs.deployment_type }}
      version: ${{ inputs.version }}
    secrets:
      DEPLOY_TOKEN: ${{ secrets.PAT }}
